#!groovy
node ("rockstor") {
   properties([ disableConcurrentBuilds()
              , parameters([string(defaultValue: 'master', description: 'Branch of MUG to build', name: 'MUG_BRANCH')])
              , [$class: 'RebuildSettings', autoRebuild: false, rebuildDisabled: false]
              , pipelineTriggers([])
              ])


   currentBuild.displayName = "#" + BUILD_ID + " (" + MUG_BRANCH + ")"
   def mvnHome
   stage('Checkout') { // for display purposes
      dir (WORKSPACE) {
        deleteDir() // clean build
      }
      retry (3) {
        checkout( [ $class: 'GitSCM'
                  , branches: [[name: params.MUG_BRANCH]]
                  , doGenerateSubmoduleConfigurations: false
                  , extensions: []
                  , submoduleCfg: []
                  , userRemoteConfigs: [[credentialsId: '0c80fc94-d6f5-489b-a850-30e0deb2273f', url: 'git@bitbucket.org:mineboxgmbh/minebox.git']]
                  ])
      }
   }
   stage('Check Build Environment') {
       sh """yum install -y rpmdevtools
             rpmdev-setuptree
          """
   }
   stage('Build RPM') {
       
       sh """mkdir -p SOURCES
             mkdir -p BUILD
             mkdir -p RPMS
             rpmbuild -bb uigateway/minebox-uigateway.spec
          """
   }
   stage('Store RPM in archive') {
      archive 'RPMS/x86_64/*.rpm'
   }
}
