@startuml

participant uploader as "uploader.sh"
participant upper as "Upper Layer\nBTRFS"
participant MineBD
participant sia as "Sia Client"
participant lower as "Lower Layer\nBTRFS Snapshot"

alt new backup

	uploader -> upper: trim unused blocks
	uploader <-- upper

	uploader -> upper: flush data to\nlower disk (sync)
	uploader <-- upper

	uploader -> lower: create snapshot
	activate lower
	uploader <-- lower

	uploader -> MineBD: Pause MineBD\nto assure "new" timestamps
	uploader <-- MineBD
else restart backup
	note over uploader: No special preparations
end

uploader -> MineBD: get list of blocks to be uploaded
uploader <-- MineBD

uploader --> sia: inform about all files to be uploaded
activate sia

sia -> lower: get data
sia <-- lower
sia -> sia: upload data

uploader -> sia: check progress & wait for upload
uploader <-- sia
deactivate sia

uploader -> uploader: bundle all "renter files" (*.sia)\nin a backup.*.zip

uploader -> lower: delete snapshot
uploader <-- lower
deactivate lower

@enduml
